### PR TITLE
Bump version to PyPSA 0.16.0

### PR DESCRIPTION
**Pull request by nworbmot**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by coroa** [comment]
Did you re-render locally?

**Comment by nworbmot** [comment]
No, I don't really know what that means...

**Comment by coroa** [comment]
@conda-forge-admin, please rerender

**Comment by coroa** [comment]
Updating the rest of the files ..., if something has changed on how they build it. This part is done automatically, if you tell the conda-forge-admin bot to do it.

**Comment by nworbmot** [comment]
OK, understood. Was wondering whether to add glpk and gurobi packages to dependencies.

**Comment by coroa** [comment]
Was wondering the same thing, don't know. I'd go without them.

**Comment by coroa** [comment]
And you're right, it's a bit strange the autotick-bot didn't pick up on the new version on PyPI. I don't know, why!

**Comment by nworbmot** [comment]
It's fine, updating the version and sha256 wasn't too much bother. I'll merge it once checks complete.

**Pull request merged**
