### PR TITLE
activate automerge

### PR DESCRIPTION
**Pull request by lkstrp**
- Activate automerge with grayskull
    - See [Configuring conda-forge.yml | conda-forge](https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot)
- Remove `xarray` duplicate
- Remove unneeded ~`deprecation`~ `packaging` package

### CODE REVIEW

**Comment by coroa** [comment]
The `automerge` setting automatically merges the prs opened by `regro-tick-bot`?

Do you have a documentation page for the caveats you can link here?

The `deprecation` and `xarray` packages are still listed as dependencies in the pyproject.toml on master:
https://github.com/PyPSA/PyPSA/blob/98efc6a7337a6981399ff64554530bcceb82dd67/pyproject.toml#L27-L41

**Comment by lkstrp** [comment]
Sorry for the typo. I meant `packaging` of course. 

I have added a link to the conda-forge configuration docs.

Yes, automerge will automatically merge the prs from `regro-cf-autotick-bot`. For a release you wouldn't need to go to the feedstock repo at all. 

Dependencies are now handled with [Grayskull](https://github.com/conda/grayskull) and the new recipe. They are basically an exact copy of [PyPSA/pyproject.toml](https://github.com/PyPSA/PyPSA/blob/master/pyproject.toml). I think if we add pip-only packages as dependencies, we might need to check the recipe.

**Comment by fneum** [comment]
Good idea! What happens if the `meta.yaml` listed dependencies become out of date?

https://github.com/conda-forge/pypsa-feedstock/blob/7ab6a088d9145c5db990702f5964097aabfe643f/recipe/meta.yaml#L23-L38

**Comment by lkstrp** [comment]
They are automatically updated in the pr. Grayskull will take care of that. As I said, the only thing I am not sure about is when we add pip-only packages as dependencies.

If you don't trust the process, we can wait for another release with changed dependencies. But even if something fails, we can push another build on the same version and no one will notice.

**Comment by fneum** [comment]
Happy to try-fail-correct.

**Comment by coroa** [comment]
LGTM

**Review by coroa — APPROVED** [review]

**Pull request merged**
